src/main/java/entity/Book.java
package entity;


import java.util.HashSet;
import java.util.Set;


public class Book implements java.io.Serializable {

    private Long id;
    private Author author;
    private Genre genre;
    private Publisher publisher;
    private String name;
    private byte[] content;
    private Integer pageCount;
    private String isbn;
    private Integer publishYear;
    private byte[] image;
    private String descr;
    private Integer rating;
    private Long voteCount;
    private Set votes = new HashSet(0);

    public Book() {
    }

    public Book(Author author, Genre genre, Publisher publisher, String name, byte[] content, int pageCount, String isbn, int publishYear, byte[] image) {
        this.author = author;
        this.genre = genre;
        this.publisher = publisher;
        this.name = name;
        this.content = content;
        this.pageCount = pageCount;
        this.isbn = isbn;
        this.publishYear = publishYear;
        this.image = image;
    }

    public Book(Author author, Genre genre, Publisher publisher, String name, byte[] content, int pageCount, String isbn, int publishYear, byte[] image, String descr, Integer rating, Long voteCount, Set votes) {
        this.author = author;
        this.genre = genre;
        this.publisher = publisher;
        this.name = name;
        this.content = content;
        this.pageCount = pageCount;
        this.isbn = isbn;
        this.publishYear = publishYear;
        this.image = image;
        this.descr = descr;
        this.rating = rating;
        this.voteCount = voteCount;
        this.votes = votes;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Author getAuthor() {
        return this.author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public Genre getGenre() {
        return this.genre;
    }

    public void setGenre(Genre genre) {
        this.genre = genre;
    }

    public Publisher getPublisher() {
        return this.publisher;
    }

    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getContent() {
        return this.content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    public Integer getPageCount() {
        return this.pageCount;
    }

    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public Integer getPublishYear() {
        return this.publishYear;
    }

    public void setPublishYear(Integer publishYear) {
        this.publishYear = publishYear;
    }

    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public Integer getRating() {
        return this.rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public Long getVoteCount() {
        return this.voteCount;
    }

    public void setVoteCount(Long voteCount) {
        this.voteCount = voteCount;
    }

    public Set getVotes() {
        return this.votes;
    }

    public void setVotes(Set votes) {
        this.votes = votes;
    }
}

src/main/java/entity/ext/BookExt.java
package entity.ext;

import entity.Book;

public class BookExt extends Book {

    public BookExt() {
        setVoteCount(0L);
        setRating(0);
    }
    
    private byte[] uploadedImage;
    private byte[] uploadedContent;

    public byte[] getUploadedContent() {
        return uploadedContent;
    }

    public void setUploadedContent(byte[] uploadedContent) {
        this.uploadedContent = uploadedContent;
    }

    public byte[] getUploadedImage() {
        return uploadedImage;
    }

    public void setUploadedImage(byte[] uploadedImage) {
        this.uploadedImage = uploadedImage;
    }

    public String getShortName(){
        if (getName()!=null && getName().length() > 20) {
            return new StringBuilder().append(getName().substring(0, 19)).append("...").toString();
        }
        
        return getName();
    }
    
    
    
    public Book getBook(){
        Book book = new Book();
        book.setAuthor(getAuthor());
        book.setContent(getUploadedContent());// записываем загруженный контент
        book.setDescr(getDescr());
        book.setGenre(getGenre());
        book.setImage(getUploadedImage());// записываем загруженное изображение
        book.setIsbn(getIsbn());
        book.setName(getName());
        book.setPageCount(getPageCount());
        book.setPublishYear(getPublishYear());
        book.setPublisher(getPublisher());
        book.setRating(getRating());
        book.setVoteCount(getVoteCount());
        book.setVotes(getVotes());
        return book;
    }
    
}

src/main/resources/java/entity/Book.java
package entity;


import java.util.HashSet;
import java.util.Set;


public class Book implements java.io.Serializable {

    private Long id;
    private Author author;
    private Genre genre;
    private Publisher publisher;
    private String name;
    private byte[] content;
    private Integer pageCount;
    private String isbn;
    private Integer publishYear;
    private byte[] image;
    private String descr;
    private Integer rating;
    private Long voteCount;
    private Set votes = new HashSet(0);

    public Book() {
    }

    public Book(Author author, Genre genre, Publisher publisher, String name, byte[] content, int pageCount, String isbn, int publishYear, byte[] image) {
        this.author = author;
        this.genre = genre;
        this.publisher = publisher;
        this.name = name;
        this.content = content;
        this.pageCount = pageCount;
        this.isbn = isbn;
        this.publishYear = publishYear;
        this.image = image;
    }

    public Book(Author author, Genre genre, Publisher publisher, String name, byte[] content, int pageCount, String isbn, int publishYear, byte[] image, String descr, Integer rating, Long voteCount, Set votes) {
        this.author = author;
        this.genre = genre;
        this.publisher = publisher;
        this.name = name;
        this.content = content;
        this.pageCount = pageCount;
        this.isbn = isbn;
        this.publishYear = publishYear;
        this.image = image;
        this.descr = descr;
        this.rating = rating;
        this.voteCount = voteCount;
        this.votes = votes;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Author getAuthor() {
        return this.author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public Genre getGenre() {
        return this.genre;
    }

    public void setGenre(Genre genre) {
        this.genre = genre;
    }

    public Publisher getPublisher() {
        return this.publisher;
    }

    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getContent() {
        return this.content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    public Integer getPageCount() {
        return this.pageCount;
    }

    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public Integer getPublishYear() {
        return this.publishYear;
    }

    public void setPublishYear(Integer publishYear) {
        this.publishYear = publishYear;
    }

    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public Integer getRating() {
        return this.rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public Long getVoteCount() {
        return this.voteCount;
    }

    public void setVoteCount(Long voteCount) {
        this.voteCount = voteCount;
    }

    public Set getVotes() {
        return this.votes;
    }

    public void setVotes(Set votes) {
        this.votes = votes;
    }
}

src/main/java/controllers/ContentController.java
package controllers;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import org.primefaces.event.FileUploadEvent;

@ManagedBean
@SessionScoped
public class ContentController implements Serializable {

    private String fileName;
    @ManagedProperty(value = "#{bookListController}")
    private BookListController bookListController;

    public BookListController getBookListController() {
        return bookListController;
    }

    public void setBookListController(BookListController bookListController) {
        this.bookListController = bookListController;
    }

    public void handleFileUpload(FileUploadEvent event) {
        bookListController.getSelectedBook().setUploadedContent(event.getFile().getContents());
        fileName = event.getFile().getFileName();
    }

    public String getFileName() {
        if (fileName!=null && fileName.length() > 20) {
            return new StringBuilder().append(fileName.substring(0, 19)).append("...").toString();
        }
        return fileName;
    }

    public boolean isShowContent() {
        if (bookListController.getSelectedBook().getUploadedContent() != null || bookListController.getSelectedBook().getContent()!=null) {
            return true;
        }

        return false;
    }

    public byte[] getUploadedContent() {
        return bookListController.getSelectedBook().getUploadedContent();
    }
}

src/main/java/controllers/ImageController.java
package controllers;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

@ManagedBean
@SessionScoped
public class ImageController implements Serializable {

    private final int IMAGE_MAX_SIZE = 204800;

    @ManagedProperty(value = "#{bookListController}")
    private BookListController bookListController;

    public BookListController getBookListController() {
        return bookListController;
    }

    public void setBookListController(BookListController bookListController) {
        this.bookListController = bookListController;
    }

    public StreamedContent getDefaultImage() {
        return getStreamedContent(bookListController.getSelectedBook().getImage());
    }

    public StreamedContent getUploadedImage() {
        return getStreamedContent(bookListController.getSelectedBook().getUploadedImage());
    }

    public void handleFileUpload(FileUploadEvent event) {
        bookListController.getSelectedBook().setUploadedImage(event.getFile().getContents());
    }

    private DefaultStreamedContent getStreamedContent(byte[] image) {

        if (image == null) {
            return null;
        }

        InputStream inputStream = null;

        try {
            inputStream = new ByteArrayInputStream(image);
            return new DefaultStreamedContent(inputStream, "image/png");

        } finally {
            try {
                inputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(ImageController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public int getImageMaxSize() {
        return IMAGE_MAX_SIZE;
    }


}

src/main/java/controllers/IndexController.java
package controllers;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;


@ManagedBean
@RequestScoped
public class IndexController {
    
    private int bookIndex = -1;

    public int getBookIndex() {
        return bookIndex;
    }
    
    public int getIncrementBookIndex() {
        return ++bookIndex;
    }   

}

src/main/webapp/pages/books.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Facelet Title</title>

    </h:head>
    <h:body>

        <ui:composition template="/templates/library.xhtml">

            <ui:define name="title">
                #{msg.book_list}
            </ui:define>

            <ui:define name="content">



                <p:growl life="3000" id="growlMessage" globalOnly="true"/> 

                <ui:include src="editBook.xhtml" />
                <ui:include src="sendMail.xhtml" />


                <h:form id="booksForm" >


                    <p:dataGrid rowIndexVar="rowIndex" columns="2" lazy="true" var="b" value="#{bookListController.bookListModel}"  id="booksList" styleClass="books_list"  paginator="true" rows="4" paginatorPosition="bottom"
                                rowsPerPageTemplate="4,10,20" paginatorTemplate="{RowsPerPageDropdown} {PageLinks}"  paginatorAlwaysVisible="true" emptyMessage="" binding="#{bookListController.dataGrid}">  




                        <div class="item">


                            <div class="image-info">



                                <h:outputLink styleClass="content_link" value="#{request.contextPath}/PdfContent"  target="_blank">                                                             
                                    <p:graphicImage value="/ShowImage?index=#{indexController.incrementBookIndex}" width="110" height="150"/>
                                    <f:param name="id" value="#{b.id}"/>
                                </h:outputLink> 

                                <p:panelGrid id="ratingPanel" columns="2" >

                                    <p:rating id="rating" value="#{b.rating}" styleClass="rating" cancel="false" stars="5" onRate="rate([{name:'bookIndex', value:#{indexController.bookIndex}}])"/>

                                    <p:outputLabel id="voteCount" value="(#{b.voteCount})" styleClass="vote-count" />


                                </p:panelGrid>

                            </div>


                            <p:remoteCommand name="rate" actionListener="#{bookListController.rate()}" global="false" oncomplete="alert('#{msg.thanks_rating}')"/>



                            <div class="info">
                                <div class="book_name">   
                                    <h:outputLink id="bookName" styleClass="title" value="#{request.contextPath}/PdfContent" target="_blank">
                                        #{b.name}
                                        <f:param name="id" value="#{b.id}"/>
                                        <f:param name="save" value="false"/>
                                    </h:outputLink>

                                    <p:tooltip for="bookName" value="#{b.descr}" showEffect="fade" hideEffect="fade" styleClass="tooltip"/>  

                                </div>
                                <span>#{b.author}</span>
                                <p><strong>#{msg.page_count}:</strong> #{b.pageCount}</p>
                                <p><strong>#{msg.publisher}</strong> #{b.publisher}</p>
                                <p><strong>#{msg.publish_year}</strong> #{b.publishYear} г.</p>
                                <p><strong>#{msg.isbn}</strong> #{b.isbn}</p>

                            </div>


                            <h:outputLink styleClass="mr" value="#{request.contextPath}/PdfContent" target="_blank">
                                <p class="read">#{msg.read}</p>
                                <f:param name="id" value="#{b.id}"/>
                                <f:param name="save" value="false"/>
                            </h:outputLink>

                            <h:outputLink styleClass="mr" value="#{request.contextPath}/PdfContent" target="_blank"> 

                                <p class="download">#{msg.download}</p>
                                <f:param name="id" value="#{b.id}"/>
                                <f:param name="filename" value="#{b.name}"/>
                                <f:param name="save" value="true"/>

                            </h:outputLink>  

                            <p:commandLink styleClass="mr" actionListener="#{bookListController.switchEditMode}" title="#{msg.edit_book}" update=":formEditBook :formEditBook:formUploadImage :formEditBook:formUploadPdf" rendered="#{request.isUserInRole('admin')}">  
                                <p class="edit">#{msg.edit}</p>
                                <f:setPropertyActionListener value="#{b}"  target="#{bookListController.selectedBook}" />
                            </p:commandLink> 

                            <p:commandLink styleClass="delete-button" title="#{msg.delete_book}" type="button" onclick="dlgDeleteBook.show()" rendered="#{request.isUserInRole('admin')}">  
                                <p class="delete">#{msg.delete}</p>
                                <f:setPropertyActionListener value="#{b}"  target="#{bookListController.selectedBook}" />
                            </p:commandLink> 


                        </div>




                    </p:dataGrid> 



                    <p:confirmDialog widgetVar="dlgDeleteBook" header="#{msg.confirm}" message="#{msg.delete_confirm}?" width="300px" styleClass="dialog_delete">    
                        <div class="button-right">
                            <h:panelGrid columns="2" style="margin:0 auto; width:150px;">
                                <p:commandLink id="btnDeletedBook" value="#{msg.yes}" action="#{bookListController.deleteBook}" styleClass="save" update=":booksForm:booksList :booksCount :growlMessage" onclick="dlgDeleteBook.hide()"/>  
                                <p:commandLink value="#{msg.no}" styleClass="cancel" onclick="dlgDeleteBook.hide()" type="button"/>       
                            </h:panelGrid>
                        </div>
                    </p:confirmDialog>  


                </h:form>






            </ui:define>

            <ui:define name="books_count">

                <div class="box-sh">

                    <h1><p:outputLabel id="booksCount" value="#{msg.book_count}:  #{bookListController.pager.totalBooksCount}" /></h1>



                    <h:form id="add-action" rendered="#{request.isUserInRole('admin')}">
                        <p:commandLink  actionListener="#{bookListController.switchAddMode}" update=":formEditBook :formEditBook:formUploadImage :formEditBook:formUploadPdf">
                            <h:outputText value="#{msg.add_book}" title="#{msg.add_book}"/>
                        </p:commandLink>
                    </h:form>


                </div>

            </ui:define>


        </ui:composition>



    </h:body>

</html>

src/main/webapp/pages/editBook.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>




        <p:dialog id="editDialog" modal="true" widgetVar="dlgEditBook" dynamic="true" resizable="false" header="#{msg.edit_book}" closable="false" onHide="#{bookListController.cancelModes()}">


            <h:form id="formEditBook"  rendered="#{bookListController.editMode or bookListController.addMode}">

                <div class="popup-info">
                    <div class="avatar-box">

                        <p:graphicImage  value="#{imageController.defaultImage}" width="110" height="150" id="bookImage" rendered="#{bookListController.editMode}"/>
                        <h:form enctype="multipart/form-data" id="formUploadImage" >
                            <p:fileUpload id="imageUpload" label="#{msg.load}" fileUploadListener="#{imageController.handleFileUpload}" update="messagesImage bookNewImage" sizeLimit="#{imageController.imageMaxSize}" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" multiple="false" auto="true"/>  
                            <p:graphicImage value="#{imageController.uploadedImage}" library="images" width="110" height="150" id="bookNewImage"/>
                            <p:messages id="messagesImage" showDetail="true" for="formUploadImage"/>
                        </h:form>



                    </div>

                    <div class="ava-info">
                        <div class="block">
                            <p>#{msg.book_name}</p>	

                            <div class="ava-form">
                                <p:inputText id="inputBookName" value="#{bookListController.selectedBook.name}" />
                            </div> 
                        </div>

                        <div class="block">
                            <p>#{msg.genre}</p>	

                            <div class="ava-form">
                                <p:selectOneMenu  value="#{bookListController.selectedBook.genre}" converter="#{genreController}"  >
                                    <f:selectItems value="${genreController.selectItems}"/>
                                </p:selectOneMenu>
                            </div> 
                        </div>

                        <div class="block">
                            <p>#{msg.author_name}</p>	

                            <div class="ava-form">
                                <p:selectOneMenu value="#{bookListController.selectedBook.author}" converter="#{authorController}">
                                    <f:selectItems value="${authorController.selectItems}"/>
                                </p:selectOneMenu>
                            </div> 
                        </div>

                        <div class="block">
                            <p>#{msg.publisher}</p>	

                            <div class="ava-form">
                                <p:selectOneMenu  value="#{bookListController.selectedBook.publisher}" converter="#{publisherController}" >
                                    <f:selectItems value="${publisherController.selectItems}"/>
                                </p:selectOneMenu>

                            </div> 
                        </div>



                        <div class="block">
                            <p>#{msg.isbn}</p>	

                            <div class="ava-form">
                                <p:inputText id="inputIsbn" value="#{bookListController.selectedBook.isbn}" />
                            </div> 
                        </div>

                        <div class="block">
                            <p>#{msg.publish_year}</p>	

                            <div class="ava-form">
                                <p:inputMask id="inputPublishYear" value="#{bookListController.selectedBook.publishYear}"  maxlength="4" placeHolder="_" mask="9999"/>
                            </div> 
                        </div>

                        <div class="block">
                            <p>#{msg.page_count}</p>	

                            <div class="ava-form">
                                <p:inputText id="inputPageCount" value="#{bookListController.selectedBook.pageCount}" />  
                            </div> 
                        </div>



                        <div class="block">
                            <p>#{msg.text}</p>	

                            <div class="ava-form">
                                <div class="loaded">


                                    <h:form enctype="multipart/form-data" id="formUploadPdf">


                                        <h:outputLink value="#{request.contextPath}/PdfContent"  target="_blank" styleClass="name" rendered="#{bookListController.editMode and not contentController.showContent}">                                                             
                                            <p:outputLabel value="#{bookListController.selectedBook.shortName}"/>
                                            <f:param name="id" value="#{bookListController.selectedBook.id}"/>
                                        </h:outputLink>    

                                        <h:outputLink id="uploadedPdfLink" value="#{request.contextPath}/UploadedPdf" styleClass="name" target="_blank" rendered="#{contentController.showContent}" >                                                             
                                            <p:outputLabel value="#{contentController.fileName}" />
                                            <f:param name="id" value="#{bookListController.selectedBook.id}"/>
                                        </h:outputLink>      


                                        <p:fileUpload  id="pdfUpload" value="" label="#{msg.load_pdf}" fileUploadListener="#{contentController.handleFileUpload}" update="@form" allowTypes="/(\.|\/)(pdf)$/" multiple="false" auto="true" styleClass="pdf-upload"/>  

                                        <p:messages id="messages-pdf" showDetail="true" for="formUploadPdf"/>
                                    </h:form>





                                </div>

                            </div> 
                        </div>


                        <div class="block">
                            <p>#{msg.descr} <span><h:outputText id="counter" /></span></p>	

                            <div class="ava-form">
                                <p:inputTextarea id="inputDescr" value="#{bookListController.selectedBook.descr}" cols="60" rows="20" maxlength="1500" counter="counter" counterTemplate="{0} #{msg.letters_left}" autoResize="false"  />

                            </div> 
                        </div>	


                    </div>








                    <div class="bottom-info">
                        <div class="error-div"> <h:messages styleClass="error" id="validationError"/></div>

                        <div class="button-right">

                            <p:commandLink id="saveButton" action="#{bookListController.saveBook()}" styleClass="save" value="#{msg.save}" onclick="this.disabled=true;" update=":formEditBook :booksForm:booksList :booksCount :growlMessage"/>                            

                            <p:commandLink action="#{bookListController.cancelModes()}"  value="#{msg.cancel}" immediate="true" global="false" styleClass="cancel"/>

                        </div>
                    </div>	

                </div>

            </h:form> 

        </p:dialog>




    </h:body>
</html>

src/main/webapp/pages/sendMail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>




        <p:dialog id="sendMailDialog" modal="true" widgetVar="dlgSendMail" dynamic="false" resizable="false" header="#{msg.send_mail}" closable="false">


            <h:form id="formSendMail">

                <div class="popup-info">

                    <div class="ava-info">
                        <div class="block">
                            <p>#{msg.mail_subject}</p>	

                            <div class="ava-form">
                                <p:inputText id="inputSubject" value="#{mailController.subject}" styleClass="mail-subject"/>
                            </div> 
                        </div>

                        <div class="block">
                            <p>#{msg.mail_text} <span><h:outputText id="counter" /></span></p>	

                            <div class="ava-form">
                                <p:inputTextarea id="inputMailText" styleClass="mail-message" value="#{mailController.message}" cols="70" rows="20" maxlength="1500" counter="counter" counterTemplate="{0} #{msg.letters_left}" autoResize="false"  />

                            </div> 
                        </div>	

                    </div>





                    <div class="bottom-info">
                        <div class="error-div"> <h:messages styleClass="error" id="validationError"/></div>

                        <div class="button-right">

                            <p:commandLink id="sendButton" onclick="this.disabled=true;" oncomplete="this.disabled=false" action="#{mailController.sendMessage()}" styleClass="save" value="#{msg.send}" update=":formSendMail :growlMessage" />                            

                            <p:commandLink action="#{mailController.hideMailForm()}"  value="#{msg.cancel}" immediate="true" global="false" styleClass="cancel"/>

                        </div>
                    </div>	

                </div>

            </h:form> 

        </p:dialog>




    </h:body>
</html>