src/main/java/controllers/BookListController.java
package controllers;

import java.io.Serializable;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import org.primefaces.component.datagrid.DataGrid;
import org.primefaces.context.RequestContext;
import org.primefaces.model.LazyDataModel;
import beans.Pager;
import db.DataHelper;
import entity.ext.BookExt;
import enums.SearchType;
import models.BookListDataModel;

@ManagedBean(eager = true)
@SessionScoped
public class BookListController implements Serializable {

    private SessionUtils sessionUtils = SessionUtils.getInstance();
    
    private DataGrid dataTable;
    private BookExt selectedBook;
    private BookExt newBook;
    private transient DataHelper dataHelper;
    private LazyDataModel<BookExt> bookListModel;
    private Long selectedAuthorId;// текущий автор книги из списка при редактировании книги
    // критерии поиска
    private char selectedLetter; // выбранная буква алфавита, по умолчанию не выбрана ни одна буква
    private SearchType selectedSearchType = SearchType.TITLE;// хранит выбранный тип поиска, по-умолчанию - по названию
    private long selectedGenreId; // выбранный жанр
    private String currentSearchString; // хранит поисковую строку
    private Pager pager;
    //-------
    private boolean editMode;// отображение режима редактирования
    private boolean addMode;// отображение режима добавление

    public BookListController() {
        pager = new Pager();
        dataHelper = new DataHelper(pager);
        bookListModel = new BookListDataModel(dataHelper, pager);
    }

    public DataHelper getDataHelper() {
        return dataHelper;
    }

    public Pager getPager() {
        return pager;
    }

    private void submitValues(Character selectedLetter, long selectedGenreId) {
        this.selectedLetter = selectedLetter;
        this.selectedGenreId = selectedGenreId;
        dataTable.setFirst(0);
    }

    //<editor-fold defaultstate="collapsed" desc="запросы в базу">
    private void fillBooksAll() {
        dataHelper.getAllBooks();
    }

    public void fillBooksByGenre() {

        imitateLoading();

        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        selectedGenreId = Long.valueOf(params.get("genre_id"));
        submitValues(' ', selectedGenreId);
        dataHelper.getBooksByGenre(selectedGenreId);

    }

    public void fillBooksByRate() {

        imitateLoading();
        dataHelper.getBooksByRate();

    }

    public void fillBooksByLetter() {

        imitateLoading();

        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        selectedLetter = params.get("letter").charAt(0);
        submitValues(selectedLetter, -1);
        dataHelper.getBooksByLetter(selectedLetter);

    }

    public void fillBooksBySearch() {

        imitateLoading();

        submitValues(' ', -1);

        if (currentSearchString.trim().length() == 0) {
            fillBooksAll();

        }

        if (selectedSearchType == SearchType.AUTHOR) {
            dataHelper.getBooksByAuthor(currentSearchString);
        } else if (selectedSearchType == SearchType.TITLE) {
            dataHelper.getBooksByName(currentSearchString);
        }

    }

    public void deleteBook() {
        dataHelper.deleteBook(selectedBook);
        dataHelper.populateList();

//        RequestContext.getCurrentInstance().execute("dlgDeleteBook.hide()");
        
        sessionUtils.showMessage("deleted");
        
        dataTable.setFirst(calcSelectedPage());

    }

    public void rate() {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        int bookIndex = Integer.parseInt(params.get("bookIndex"));

        BookExt book = pager.getList().get(bookIndex);

        dataHelper.rateBook(book, sessionUtils.getUserName());

    }

    public void saveBook() {

        if (!validateFields()) {
            return;
        }

        if (editMode) {
            dataHelper.updateBook(selectedBook);
        } else if (addMode) {
            dataHelper.addBook(selectedBook.getBook());
        }

        cancelModes();
        dataHelper.populateList();
        
        sessionUtils.showMessage("updated");

        dataTable.setFirst(calcSelectedPage());
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="режим редактирования">
    public void switchEditMode() {
        editMode = true;
        RequestContext.getCurrentInstance().execute("dlgEditBook.show()");

    }

    public void switchAddMode() {
        addMode = true;
        selectedBook = new BookExt();
        selectedBook.setGenre(dataHelper.getGenre(selectedGenreId));
        RequestContext.getCurrentInstance().execute("dlgEditBook.show()");

    }
    
  

    public void cancelModes() {
        if (addMode) {
            addMode = false;
        }

        if (editMode) {
            editMode = false;
        }

        if (selectedBook != null) {
            selectedBook.setUploadedContent(null);
            selectedBook.setUploadedImage(null);
        }

        RequestContext.getCurrentInstance().execute("dlgEditBook.hide()");
    }

    //</editor-fold>
    public Character[] getRussianLetters() {
        Character[] letters = new Character[]{'А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ё', 'Ж', 'З', 'И', 'Й', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ъ', 'Ы', 'Ь', 'Э', 'Ю', 'Я',};
        return letters;
    }

    public void searchStringChanged(ValueChangeEvent e) {
        currentSearchString = e.getNewValue().toString();
    }

    public void searchTypeChanged(ValueChangeEvent e) {
        selectedSearchType = (SearchType) e.getNewValue();
    }

    private int calcSelectedPage() {
        int page = dataTable.getPage();// текущий номер страницы (индексация с нуля)

        int leftBound = pager.getTo() * (page - 1);
        int rightBound = pager.getTo() * page;

        boolean goPrevPage = pager.getTotalBooksCount() > leftBound & pager.getTotalBooksCount() <= rightBound;


        if (goPrevPage) {
            page--;
        }

        return (page > 0) ? page * pager.getTo() : 0;
    }

    //<editor-fold defaultstate="collapsed" desc="гетеры сетеры">
    public boolean isEditMode() {
        return editMode;
    }

    public boolean isAddMode() {
        return addMode;
    }

    public String getSearchString() {
        return currentSearchString;
    }

    public void setSearchString(String searchString) {
        this.currentSearchString = searchString;
    }

    public SearchType getSearchType() {
        return selectedSearchType;
    }

    public void setSearchType(SearchType searchType) {
        this.selectedSearchType = searchType;
    }

    public long getSelectedGenreId() {
        return selectedGenreId;
    }

    public void setSelectedGenreId(int selectedGenreId) {
        this.selectedGenreId = selectedGenreId;
    }

    public char getSelectedLetter() {
        return selectedLetter;
    }

    public void setSelectedLetter(char selectedLetter) {
        this.selectedLetter = selectedLetter;
    }

    public Long getSelectedAuthorId() {
        return selectedAuthorId;
    }

    public void setSelectedAuthorId(Long selectedAuthorId) {
        this.selectedAuthorId = selectedAuthorId;
    }

    public LazyDataModel<BookExt> getBookListModel() {
        return bookListModel;
    }

    public void setSelectedBook(BookExt selectedBook) {
        this.selectedBook = selectedBook;
    }

    public BookExt getSelectedBook() {
        return selectedBook;
    }

    public DataGrid getDataGrid() {
        return dataTable;
    }

    public void setDataGrid(DataGrid dataTable) {
        this.dataTable = dataTable;
    }

    public BookExt getNewBook() {
        if (newBook == null) {
            newBook = new BookExt();
        }
        return newBook;
    }

    public void setNewBook(BookExt newBook) {
        this.newBook = newBook;
    }

    //</editor-fold>
    private void imitateLoading() {
//        try {
//            Thread.sleep(1000);// имитация загрузки процесса
//        } catch (InterruptedException ex) {
//            Logger.getLogger(BookListController.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private boolean validateFields() {

        if (sessionUtils.isNullOrEmpty(selectedBook.getAuthor())
                || sessionUtils.isNullOrEmpty(selectedBook.getDescr())
                || sessionUtils.isNullOrEmpty(selectedBook.getGenre())
                || sessionUtils.isNullOrEmpty(selectedBook.getIsbn())
                || sessionUtils.isNullOrEmpty(selectedBook.getName())
                || sessionUtils.isNullOrEmpty(selectedBook.getPageCount())
                || sessionUtils.isNullOrEmpty(selectedBook.getPublishYear())
                || sessionUtils.isNullOrEmpty(selectedBook.getPublisher())) {
            sessionUtils.failValidation("error_fill_all_fields");
            return false;

        }
        
        
        if (dataHelper.isIsbnExist(selectedBook.getIsbn(), selectedBook.getId())){
            sessionUtils.failValidation("error_isbn_exist");
            return false;            
        }

        if (addMode) {

            if (selectedBook.getUploadedContent() == null) {
                sessionUtils.failValidation("error_load_pdf");
                return false;
            }

            if (selectedBook.getUploadedImage() == null) {
                sessionUtils.failValidation("error_load_image");
                return false;
            }

        }


        return true;


    }

   

   
}

src/main/java/controllers/ContentController.java
package controllers;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import org.primefaces.event.FileUploadEvent;

@ManagedBean
@SessionScoped
public class ContentController implements Serializable {

    private String fileName;
    @ManagedProperty(value = "#{bookListController}")
    private BookListController bookListController;

    public BookListController getBookListController() {
        return bookListController;
    }

    public void setBookListController(BookListController bookListController) {
        this.bookListController = bookListController;
    }

    public void handleFileUpload(FileUploadEvent event) {
        bookListController.getSelectedBook().setUploadedContent(event.getFile().getContents());
        fileName = event.getFile().getFileName();
    }

    public String getFileName() {
        if (fileName!=null && fileName.length() > 20) {
            return new StringBuilder().append(fileName.substring(0, 19)).append("...").toString();
        }
        return fileName;
    }

    public boolean isShowContent() {
        if (bookListController.getSelectedBook().getUploadedContent() != null || bookListController.getSelectedBook().getContent()!=null) {
            return true;
        }

        return false;
    }

    public byte[] getUploadedContent() {
        return bookListController.getSelectedBook().getUploadedContent();
    }
}

src/main/java/controllers/GenreController.java
package web.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import beans.Pager;
import comparators.ListComparator;
import db.DataHelper;
import entity.ext.GenreExt;

@ManagedBean
@SessionScoped
public class GenreController implements Serializable, Converter {

    private List<SelectItem> selectItems = new ArrayList<SelectItem>();
    private Map<Long, GenreExt> map;
    private List<GenreExt> list;
    private Pager pager;
    private DataHelper dataHelper;
    @ManagedProperty(value = "#{bookListController}")
    private BookListController bookListController;

    @PostConstruct
    public void init() {
        pager = bookListController.getPager();
        dataHelper = bookListController.getDataHelper();

        map = new HashMap<Long, GenreExt>();
        list = dataHelper.getAllGenres();
        Collections.sort(list, ListComparator.getInstance());
        
        list.add(0, createEmptyGenre());

        for (GenreExt genre : list) {
            map.put(genre.getId(), genre);
            selectItems.add(new SelectItem(genre, genre.getName()));
        }

    }

    public List<SelectItem> getSelectItems() {
        return selectItems;
    }

    public List<GenreExt> getGenreList() {
        return list;
    }

    @Override
    public Object getAsObject(FacesContext context, UIComponent component, String value) {
        return map.get(Long.valueOf(value));
    }

    @Override
    public String getAsString(FacesContext context, UIComponent component, Object value) {
        return ((GenreExt) value).getId().toString();
    }

    public BookListController getBookListController() {
        return bookListController;
    }

    public void setBookListController(BookListController bookListController) {
        this.bookListController = bookListController;
    }

    private GenreExt createEmptyGenre() {
        GenreExt genre = new GenreExt();
        genre.setId(-1L);
        genre.setName("");
        return genre;
    }
}

src/main/resources/java/controllers/ContentController.java
package controllers;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import org.primefaces.event.FileUploadEvent;

@ManagedBean
@SessionScoped
public class ContentController implements Serializable {

    private String fileName;
    @ManagedProperty(value = "#{bookListController}")
    private BookListController bookListController;

    public BookListController getBookListController() {
        return bookListController;
    }

    public void setBookListController(BookListController bookListController) {
        this.bookListController = bookListController;
    }

    public void handleFileUpload(FileUploadEvent event) {
        bookListController.getSelectedBook().setUploadedContent(event.getFile().getContents());
        fileName = event.getFile().getFileName();
    }

    public String getFileName() {
        if (fileName!=null && fileName.length() > 20) {
            return new StringBuilder().append(fileName.substring(0, 19)).append("...").toString();
        }
        return fileName;
    }

    public boolean isShowContent() {
        if (bookListController.getSelectedBook().getUploadedContent() != null || bookListController.getSelectedBook().getContent()!=null) {
            return true;
        }

        return false;
    }

    public byte[] getUploadedContent() {
        return bookListController.getSelectedBook().getUploadedContent();
    }
}

src/main/webapp/templates/content.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="style_main.css"  />
    </h:head>
    <h:body>
        <ui:composition>
            content
        </ui:composition>

    </h:body>
</html>

src/main/webapp/templates/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="style_main.css"  />
    </h:head>
    <h:body>
        <ui:composition>
            footer
        </ui:composition>

    </h:body>
</html>

src/main/webapp/templates/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"

      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="style_main.css"  />
    </h:head>
    <h:body>
        <ui:composition>


            <div class="logo">
                <h:graphicImage library="images" name="library.png" />

            </div>
            <div class="descr">
                <h3>#{msg.welcome_title}</h3>

            </div>

            <div class="welcome">


                <ui:include src="/templates/locales.xhtml"/>


                <p><h5>#{msg.welcome},  #{user.username}</h5></p>

                <h:form>
                    <h:commandLink action="#{user.logout()}" value="#{msg.exit}"/>
                </h:form>
            </div>


            <div class="search_div">
                <h:form styleClass="search_form">
                    <h:inputText id="search_string" styleClass="search_string" value="#{bookListController.searchString}" valueChangeListener="#{bookListController.searchStringChanged}">
                        <f:ajax  event="change" />
                    </h:inputText>
                    <h:commandButton value="#{msg.search}" styleClass="search_button">
                        <f:ajax onevent="showProgress" execute="@form" render=":booksForm:booksList @form :lettersForm :pages1 :pages2 :booksCount" listener="#{bookListController.fillBooksBySearch()}"/>
                    </h:commandButton>
                </h:form>

                <h:form styleClass="search_type">
                    <h:selectOneMenu styleClass="search_type_dropdown" value="#{bookListController.searchType}" valueChangeListener="#{bookListController.searchTypeChanged}">
                        <f:selectItems value="${searchTypeController.searchList}" />
                        <f:ajax event="change"/>
                    </h:selectOneMenu>

                </h:form>

            </div>

            <div class="letters">
                <h:form id="lettersForm">
                    <ui:repeat value="#{bookListController.russianLetters}" var="letter">

                        <h:commandLink value="#{letter}" styleClass="#{letter == bookListController.selectedLetter ? 'selected_letter':''}">

                            <f:param name="letter" value="#{letter}" />
                            <f:ajax onevent="showProgress" event="click" render=":booksForm:booksList @form :lettersForm :pages1 :pages2 :booksCount" listener="#{bookListController.fillBooksByLetter()}"/>

                        </h:commandLink>

                    </ui:repeat>
                </h:form>

            </div>

        </ui:composition>

    </h:body>
</html>

src/main/webapp/templates/left_menu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="style_main.css"  />

        

    </h:head>
    <h:body>
        <ui:composition>
          
            <h4>#{msg.genres}</h4>

            <h:form styleClass="genres">
                <ui:repeat value="#{genreController.genreList}" var="g">

                    <h:commandLink value="#{g.name}" styleClass="#{g.id == bookListController.selectedGenreId ? 'selected_link':''}">

                        <f:param name="genre_id" value="#{g.id}" />
                        <f:ajax onevent="showProgress" event="click" render=":booksForm:booksList @form :lettersForm :pages1 :pages2 :booksCount" listener="#{bookListController.fillBooksByGenre()}"/>

                    </h:commandLink>

                </ui:repeat>

            </h:form>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/library_template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">

    <f:view locale="#{localeChanger.currentLocale}">  
        <h:head>
            <title><ui:insert name="title"/></title>
            <h:outputStylesheet library="css" name="style_main.css"  />
            <h:outputScript library="js" name="library.js" target="head"/>
        </h:head>
        <h:body>



            <div id="loading_wrapper">
                <p>#{msg.loading}...</p>
            </div>

            <div class="container">

                <div class="header">
                    <ui:insert name="header">
                        <ui:include src="/templates/header.xhtml"/>
                    </ui:insert>                 
                </div>

                <div class="middle">
                    <div class="left_menu">
                        <ui:insert name="left_menu">
                            <ui:include src="/templates/left_menu.xhtml"/>
                        </ui:insert>                 
                    </div>

                    <div class="content">

                        <p><strong><ui:insert name="books_count"/></strong></p>

                        <div class="pager">
                            <h:panelGroup id="pages1" layout="block"> <ui:insert name="paginator"/> </h:panelGroup>

                        </div>

                        <div class="content_books">
                            <ui:insert name="content">
                                <ui:include src="/templates/content.xhtml"/>
                            </ui:insert>    
                        </div>

                        <div class="pager">

                            <h:panelGroup id="pages2" layout="block"> <ui:insert name="paginator"/> </h:panelGroup>

                        </div>

                    </div>



                    <div style="clear: both;">&nbsp;</div>

                </div>

                <div class="footer">
                    <ui:insert name="footer">
                        <ui:include src="/templates/footer.xhtml"/>
                    </ui:insert>                 
                </div>


            </div>

        </h:body>
    </f:view>
</html>

src/main/webapp/templates/locales.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:fn="http://java.sun.com/jsp/jstl/functions">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="style_main.css"  />
    </h:head>
    <h:body>
        <ui:composition>

            <div class="locales">
                <h:form>

                    <h:commandLink action="#{localeChanger.changeLocale('en')}">
                        <h:graphicImage library="images" name="eng.png" title="#{msg.english}" />
                        <f:ajax render=":login_div :lib_title" execute="@form" disabled="#{fn:contains(request.requestURL, 'books.xhtml')}"/>
                        <f:ajax render="@all" execute="@form" disabled="#{not fn:contains(request.requestURL, 'books.xhtml')}"/>
                    </h:commandLink>
                    <h:commandLink action = "#{localeChanger.changeLocale('ru')}">
                        <h:graphicImage library="images" name="rus.png" title="#{msg.russian}"/>
                        <f:ajax render=":login_div :lib_title" execute="@form" disabled="#{fn:contains(request.requestURL, 'books.xhtml')}"/>
                        <f:ajax render="@all" execute="@form" disabled="#{not fn:contains(request.requestURL, 'books.xhtml')}"/>
                    </h:commandLink>

                </h:form>
            </div>

        </ui:composition>
    </h:body>
</html>